apiVersion: v1
kind: Service
metadata:
  name: scte35-processor
  namespace: video-platform
  labels:
    app: scte35-processor
spec:
  selector:
    app: scte35-processor
  type: ClusterIP
  ports:
    - name: http
      port: 8001
      targetPort: 8001
      protocol: TCP
