server {
    listen 80;
    server_name _;

    # HLS / DASH origin
    location /live/ {
        alias /var/www/hls/live/;
        types {
            application/vnd.apple.mpegurl  m3u8;
            video/mp2t                     ts;
            application/dash+xml           mpd;
            video/mp4                      mp4 m4s;
        }
        add_header Cache-Control "no-cache";
    }

    # Ad Insertion service
    location /ads/ {
        proxy_pass         http://ad-server:3000/ads/;
        proxy_http_version 1.1;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Operator dashboard
    location / {
        proxy_pass         http://dashboard:3002;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade $http_upgrade;
        proxy_set_header   Connection "upgrade";
        proxy_set_header   Host $host;
    }
}
