apiVersion: v1
kind: Service
metadata:
  name: shaka-packager
  namespace: video-platform
  labels:
    app: shaka-packager
spec:
  selector:
    app: shaka-packager
  type: ClusterIP
  ports:
    - name: http
      port: 8003
      targetPort: 8003
      protocol: TCP
